### ISSUE TITLE
Should identity wallet interactions be explicitly out of scope?

### ISSUE THREAD

**Issue by timcappalli** [fedidcg/fedidcg.github.io#10]
Brought up during charter discussion at TPAC. Should we explicitly say that identity wallet interactions should be out of scope, due to OpenID4VC family similarities to OpenID Connect?

**Comment by kdenhartog** [comment]
I'd be a +1 to explicitly calling this out of scope for now even if we decided to operate with a living document process. My expectation is that we can address this later after a re-chartering discussion and at that time can be more fine grained as we achieve a better understanding of the harms we may introduce and additional understanding of the advantages and disadvantages that come with making this easier inside the browser.

With that said, I'm acutely aware that the only way we're going to gain better insight into this is going to be through further discussion and experimentation identity wallet interactions. So, I'd be favorable to allowing those discussions in the CG for the time being to see where they lead.
