### ISSUE TITLE
Jargon

### ISSUE THREAD

**Issue by mnot** [fedidcg/fedidcg.github.io#4]
The draft charter contains unexpanded and unexplained terms like 'IdP' and 'RP'. 

While these are well-understood in the identity community, the charter needs to be read and understood by a broader audience -- including AC reps from companies that aren't in the identity space.

**Comment by TallTed** [comment]
Please be specific about which document is the focus of your comments. I'm *guessing* that you mean [this `Proposed-WG-WebIdentityCredentials.md`](https://github.com/fedidcg/fedidcg.github.io/blob/main/charters/Proposed-WG-WebIdentityCredentials.md). Before I or anyone else spends time trying to address your comments by editing the wrong document, please confirm whether my guess is currect.

**Comment by mnot** [comment]
Yes.

**Comment by timcappalli** [comment]
Addressed in #13
