### ISSUE TITLE
participation structures

### ISSUE THREAD

**Issue by martinthomson** [fedidcg/fedidcg.github.io#8]
I did not read [this](https://github.com/fedidcg/fedidcg.github.io/blob/main/charters/Proposed-WG-WebIdentityCredentials.md#participation) as *requiring* two of each:

> To be successful, this Working Group is expected to have participation representative of at least two of each of the following: large-scale Identity Provider (IdP) operators, large-scale Relying Parties (RPs), federation operators, and two browser vendors.

This is great as an aspiration, but not as a requirement.  However, discussion in the room seemed to indicate that the WG would not work without meeting this.  That is, it seems to be interpreted as a requirement.  Please do not *require* this.  I suggest that you strike the "at least two" portion of this statement.

**Comment by timcappalli** [comment]
general consensus at TPAC charter meeting that this is a good idea
